package IleriProg_DonemOdevi;

import static IleriProg_DonemOdevi.DosyaGoruntule.LINE_SEP;
import static IleriProg_DonemOdevi.DosyaYukle.file;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author merve
 */
public class OrtakPaylasim extends javax.swing.JFrame {

    DefaultTableModel dtmOrtak;
    DefaultTableModel dtmKisisel;
    static Student s1;

    String kolonIsimleri[] = {"Ders Adı", "Dosya No", "Dosya Adı", "Dosya Sahibi", "Yük.Tarihi"};
    String kolonIsimleri2[] = {"Ders Adı", "Dosya No", "Dosya Adı", "Yük.Tarihi"};

    /**
     * Creates new form OrtakPaylasim
     */
    public OrtakPaylasim() {
        initComponents();
        this.getContentPane().setBackground(new Color(224, 228, 247));
        // jPanel2.setBackground(new Color(215,225,255));
        ortakTablo.setBackground(new Color(254, 254, 254));
        kisiselTablo.setBackground(new Color(254, 254, 254));
    }

    public OrtakPaylasim(Student s) {
        initComponents();
        this.getContentPane().setBackground(new Color(224, 228, 247));
        //  jPanel2.setBackground(new Color(215,224,255));
        ortakTablo.setBackground(new Color(254, 254, 254));
        kisiselTablo.setBackground(new Color(254, 254, 254));
        s1 = s;

        jTextField1.setText(s.name);
        jTextField2.setText(String.valueOf(s.id));

        ResetDtm1();
        ResetDtm2();
        System.out.println("dosya sayısı : " + Database.dosyalar.size());

        for (Dosya d : Database.dosya_data1) {
            int no = d.dosya_no;
            String adi = d.dosya_ismi;
            String ders = d.ders_adi;
            String tarih = d.yuklenme_tarihi;
            Student sahibi = d.dosya_sahibi;
            Object o[] = {ders, no, adi, sahibi.name, tarih};
            dtmOrtak.addRow(o);
            
            System.out.println(d.dosya_sahibi.name);
            
            if (d.dosya_sahibi == s) {

                Object o2[] = {ders, no, adi, tarih};
                dtmKisisel.addRow(o2);
            }
        }
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ortakTablo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        kisiselTablo = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(215, 224, 240));
        setForeground(new java.awt.Color(254, 254, 254));

        jButton1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(138, 10, 237));
        jButton1.setText("Görüntüle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(138, 10, 237));
        jButton2.setText("Kaydet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(138, 10, 237));
        jLabel1.setText("           ORTAK PAYLAŞIM ALANI");

        ortakTablo.setBackground(new java.awt.Color(254, 254, 254));
        ortakTablo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ortakTablo.setForeground(java.awt.Color.black);
        ortakTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ortakTablo.setGridColor(java.awt.Color.lightGray);
        jScrollPane2.setViewportView(ortakTablo);

        jPanel2.setBackground(new java.awt.Color(183, 204, 238));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField1.setBackground(new java.awt.Color(250, 250, 250));
        jTextField1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(94, 47, 130));
        jTextField1.setDisabledTextColor(new java.awt.Color(156, 85, 211));
        jTextField1.setEnabled(false);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(250, 250, 250));
        jTextField2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(94, 47, 130));
        jTextField2.setDisabledTextColor(new java.awt.Color(156, 85, 211));
        jTextField2.setEnabled(false);

        jButton5.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(138, 10, 237));
        jButton5.setText("Çıkış");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(138, 10, 237));
        jLabel2.setText("ÖĞRENCİ ADI:");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(138, 10, 237));
        jLabel4.setText("ÖĞRENCİ NO:");

        jButton3.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(138, 10, 237));
        jButton3.setText("Dosya Yükle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        kisiselTablo.setBackground(new java.awt.Color(254, 254, 254));
        kisiselTablo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kisiselTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ders Adı", "Dosya No", "Dosya Adı", "Yüklenme Tarihi"
            }
        ));
        kisiselTablo.setGridColor(java.awt.Color.lightGray);
        kisiselTablo.setInheritsPopupMenu(true);
        jScrollPane3.setViewportView(kisiselTablo);

        jButton4.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(138, 10, 237));
        jButton4.setText("Dosya Sil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(138, 10, 237));
        jLabel5.setText("Yüklü Dosyalarım");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IleriProg_DonemOdevi/images.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 159, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(167, 167, 167))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(137, 137, 137)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private void ResetDtm1() {
        dtmOrtak = new DefaultTableModel();
        dtmOrtak.setColumnIdentifiers(kolonIsimleri);
        ortakTablo.setModel(dtmOrtak);
    }

    private void ResetDtm2() {
        dtmKisisel = new DefaultTableModel();
        dtmKisisel.setColumnIdentifiers(kolonIsimleri2);
        kisiselTablo.setModel(dtmKisisel);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int key = Integer.parseInt(dtmOrtak.getValueAt(ortakTablo.getSelectedRow(), 1).toString());
        System.out.println("key: " + key);

        File f = Database.dosyalar.get(key).dosya;
        System.out.println("dosyanın yolu : " + f.getAbsolutePath());
        DosyaGoruntule dosyaGoruntule;
        try {
            dosyaGoruntule = new DosyaGoruntule(f);
            dosyaGoruntule.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(OrtakPaylasim.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DosyaYukle dosyaYukle = new DosyaYukle(Database.std.get(s1.id));
        dosyaYukle.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        OgrenciGiris giris = new OgrenciGiris(false);
        giris.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int key = Integer.parseInt(dtmKisisel.getValueAt(kisiselTablo.getSelectedRow(), 1).toString());
        System.out.println("silinecek key: " + key);

        File f = Database.dosyalar.get(key).dosya;
        System.out.println("dosyanın yolu : " + f.getAbsolutePath());
        Database.std.get(s1.id).dosyalar.remove(Database.dosyalar.get(key));
        Database.dosya_data1.remove(Database.dosyalar.get(key));
        Database.dosyalar.remove(key);

        ResetDtm1();
        ResetDtm2();

        for (Dosya d : Database.dosya_data1) {
            int no = d.dosya_no;
            String adi = d.dosya_ismi;
            String ders = d.ders_adi;
            String tarih = d.yuklenme_tarihi;
            Student sahibi = d.dosya_sahibi;
            Object o[] = {ders, no, adi, sahibi.name, tarih};
            dtmOrtak.addRow(o);

            if (d.dosya_sahibi == s1) {
                Object o2[] = {ders, no, adi, tarih};
                dtmKisisel.addRow(o2);
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed
    static void writeLines(File f) throws IOException {
        OutputStream os = new FileOutputStream(f);
        FileOutputStream fos;
        try {
            fos = new FileOutputStream(f);
            BufferedOutputStream bos = new BufferedOutputStream(fos);
            //  byte[] ba = new byte[];
            //  fos.write(ba);
            fos.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(OrtakPaylasim.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int key = Integer.parseInt(dtmOrtak.getValueAt(ortakTablo.getSelectedRow(), 1).toString());
        File f = Database.dosyalar.get(key).dosya;
        System.out.println(f.getName());
        if (f.getName().contains("txt") || f.getName().contains("dat")) {
            InputStream is;
            try {
                File outputFile = new File(f.getName());
                is = new FileInputStream(f);
                byte[] ba = new byte[is.available()];
                is.read(ba);
                is.close();
                FileOutputStream fos;
                fos = new FileOutputStream(outputFile);
                BufferedOutputStream bos = new BufferedOutputStream(fos);
                bos.write(ba);
                bos.close();
                JOptionPane.showMessageDialog(this, "Dosyanız şuraya kaydedildi:\n" + outputFile.getAbsolutePath(), "", JOptionPane.INFORMATION_MESSAGE);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(OrtakPaylasim.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(OrtakPaylasim.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (f.getName().contains("png") || f.getName().contains("jpeg")
                || f.getName().contains("PNG") || f.getName().contains("JPG") || f.getName().contains("jpg")) {
            try {

                BufferedImage bi = ImageIO.read(f);
                File outputFile = new File(f.getName());
                System.out.println("--- " + f.getName());
                String type = f.getName().substring(f.getName().length() - 3);
                if (type.equals("jpg") || type.equals("JPG")) {
                    ImageIO.write(bi, "jpeg", outputFile);
                } else {
                    ImageIO.write(bi, "png", outputFile);
                }
                JOptionPane.showMessageDialog(this, "Dosyanız şuraya kaydedildi:\n" + outputFile.getAbsolutePath(), "", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                System.out.println("hata!!");
            }

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrtakPaylasim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrtakPaylasim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrtakPaylasim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrtakPaylasim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrtakPaylasim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable kisiselTablo;
    private javax.swing.JTable ortakTablo;
    // End of variables declaration//GEN-END:variables

}
